"""Second stage of tools/atlas_build.py: turn the cached downloads into the data modules js/data/atlas_*.js.

Not run directly — use `python3 tools/atlas_build.py build [--cache DIR] [--out js/data]`.

Storage: numeric tables are quantised to 8/16-bit integers, DEFLATE-compressed and written as base64 text
({ n: byte length, z: base64 }); js/data/atlas_codec.js decodes them. Small tables stay plain JSON.
"""
import base64, csv, datetime, glob, json, math, os, zlib
import numpy as np
import atlas_build as B

MONTHS = ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC']


def pack(arr):
    raw = arr if isinstance(arr, (bytes, bytearray)) else np.ascontiguousarray(arr).tobytes()
    c = zlib.compressobj(9, zlib.DEFLATED, -15)
    return {'n': len(raw), 'z': base64.b64encode(c.compress(raw) + c.flush()).decode()}


def write_module(out, name, header, exports):
    path = os.path.join(out, name)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(''.join('// ' + ln + '\n' for ln in header))
        for k, v in exports.items():
            f.write('export const %s = %s;\n' % (k, json.dumps(v, separators=(',', ':'), ensure_ascii=False)))
    size = os.path.getsize(path)
    B.log('wrote %-22s %8.1f kB' % (name, size / 1000))
    return size


def mtime_month(*paths):
    t = max(os.path.getmtime(p) for p in paths)
    return datetime.datetime.utcfromtimestamp(t).strftime('%Y-%m')


def compand(a, k):
    """Signed square-root companding to int8: fine steps near sea level, coarse steps at depth / altitude."""
    return np.clip(np.round(np.sign(a) * np.sqrt(np.abs(a)) * k), -127, 127).astype(np.int8)


# ------------------------------------------------------------------------------------------------ relief
def build_relief(cache, out):
    fine = B.load_relief(cache)  # 1.5' samples, row 0 = south
    sea = fine < 0
    # base grid: 0.25 degree cell means
    g25 = B.block_mean(fine, 10)
    q = compand(g25, 1.2)
    d = q.copy(); d[:, 1:] = q[:, 1:] - q[:, :-1]
    # coastal tiles: every 0.25 degree cell with a shoreline, plus its shallow sea neighbours, at 0.05 degrees.
    # A 0.05 degree value is the mean of the majority class (sea or land) of its samples, so that a cell which is
    # mostly water reports the depth of the water, not an average pulled up by the land next to it.
    fr = sea.reshape(720, 10, 1440, 10).mean(axis=(1, 3))
    lat = -90 + 0.125 + 0.25 * np.arange(720)
    band = ((lat > -57) & (lat < 72))[:, None]
    coast = (fr > 0.02) & (fr < 0.98) & band
    nb = coast.copy()
    for di in (-1, 0, 1):
        for dj in (-1, 0, 1):
            nb |= np.roll(np.roll(coast, di, 0), dj, 1)
    mask = nb & (fr > 0.02) & ((g25 > -300) | coast) & band
    f4 = fine.reshape(3600, 2, 7200, 2).astype(np.float64)
    s4 = (f4 < 0)
    nsea = s4.sum(axis=(1, 3))
    sea_mean = np.where(nsea > 0, (f4 * s4).sum(axis=(1, 3)) / np.maximum(nsea, 1), 0)
    land_mean = np.where(nsea < 4, (f4 * ~s4).sum(axis=(1, 3)) / np.maximum(4 - nsea, 1), 0)
    c5 = np.where(nsea >= 2, np.minimum(sea_mean, -1), land_mean)
    ii, jj = np.nonzero(mask)
    t = np.stack([c5[i * 5:(i + 1) * 5, j * 5:(j + 1) * 5] for i, j in zip(ii, jj)])
    tq = compand(t, 2.0)
    tq[(t < 0) & (tq == 0)] = -1
    tq[:, 1::2, :] = tq[:, 1::2, ::-1]  # boustrophedon order keeps neighbours adjacent
    tq = tq.reshape(len(tq), 25)
    td = tq.copy(); td[:, 1:] = tq[:, 1:] - tq[:, :-1]
    ids = (ii * 1440 + jj).astype(np.int64)
    idd = np.diff(ids, prepend=0).astype('<i4')
    relief = {'source': 'NOAA NCEI global DEM mosaic (ETOPO 2022, GEBCO and regional surveys), 1.5 arc-minute export', 'vintage': mtime_month(*glob.glob(os.path.join(cache, 'relief/*.tif'))),
              'base': {'step': 0.25, 'nlat': 720, 'nlon': 1440, 'k': 1.2, 'data': pack(d)},
              'tiles': {'step': 0.05, 'per': 5, 'k': 2.0, 'count': int(len(ids)), 'ids': pack(idd), 'data': pack(td)}}
    return write_module(out, 'atlas_relief.js', [
        'Built-in world atlas — seabed depth and land elevation. Generated by tools/atlas_build.py; do not edit.',
        'Source: NOAA NCEI global DEM mosaic. Base grid: 0.25 degree cell means, whole world. Coastal tiles: 0.05 degree',
        '(about 5 km) values for every 0.25 degree cell that holds a shoreline and its shallow sea neighbours, 57 S - 72 N;',
        'each 0.05 degree value is the mean of the majority class (sea or land) of the 1.5 arc-minute samples inside it.',
        'Values are square-root companded to 8 bits: z = sign(q) * (q / k)^2 metres.'], {'RELIEF': relief})


# ------------------------------------------------------------------------------------------------ ocean
def harmonics(m):
    """Annual mean and first two harmonics (a1, b1, a2, b2) of 12 monthly values; value(m) = mean + sum a_k cos + b_k sin."""
    ok = np.isfinite(m)
    if ok.sum() < 8:
        return None
    ph = 2 * np.pi * np.arange(12) / 12
    A = np.stack([np.ones(12), np.cos(ph), np.sin(ph), np.cos(2 * ph), np.sin(2 * ph)], axis=1)
    c, *_ = np.linalg.lstsq(A[ok], m[ok], rcond=None)
    return c


def build_ocean(cache, out):
    from scipy.io import netcdf_file
    import warnings
    # ---- salinity: SeaDataCloud 0.25 degree monthly climatology, 5 m level
    S = []
    for m in range(12):
        f = netcdf_file(os.path.join(cache, 'ocean/Salinity_%02d.nc' % m), 'r', mmap=False)
        a = f.variables['Salinity'][0, 0].astype(np.float64).copy()
        a[a > 1e30] = np.nan
        S.append(a[:640])  # 80 S ... 79.75 N
    S = np.array(S)
    S[(S <= 0) | (S > 50)] = np.nan
    F = 4  # 0.25 degree nodes per cell  ->  1 degree cells
    nlat, nlon = 640 // F, 1440 // F
    with warnings.catch_warnings():
        warnings.simplefilter('ignore')
        # cell value of a month: median of its nodes (robust against isolated artefacts of the analysis)
        Sc = np.nanmedian(S.reshape(12, nlat, F, nlon, F).transpose(0, 1, 3, 2, 4).reshape(12, nlat, nlon, F * F), axis=3)
    # ---- temperature: CoralTemp monthly means sampled every 0.25 degrees, mean of each calendar month over SST_YEARS
    acc = np.zeros((12, 720, 1440)); cnt = np.zeros((12, 720, 1440))
    for y in B.SST_YEARS:
        for m in range(12):
            f = netcdf_file(os.path.join(cache, 'sst/crw_%d_%02d.nc' % (y, m + 1)), 'r', mmap=False)
            v = f.variables['sea_surface_temperature']
            a = v[0].astype(np.float64) * getattr(v, 'scale_factor', 1.0) + getattr(v, 'add_offset', 0.0)
            if f.variables['latitude'][0] > f.variables['latitude'][-1]:
                a = a[::-1]
            ok = (a > -5) & (a < 45)
            acc[m] += np.where(ok, a, 0); cnt[m] += ok
    clim = np.where(cnt >= max(2, len(B.SST_YEARS) // 2), acc / np.maximum(cnt, 1), np.nan)[:, 40:680]  # 80 S ... 80 N
    ph = 2 * np.pi * np.arange(12) / 12
    def reduce(f):  # block mean over f x f samples, then mean and two harmonics (cells need all twelve months)
        with warnings.catch_warnings():
            warnings.simplefilter('ignore')
            g = np.nanmean(clim.reshape(12, 640 // f, f, 1440 // f, f), axis=(2, 4))
        ok = np.isfinite(g).all(axis=0)
        g0 = np.nan_to_num(g)
        mean = g0.mean(axis=0)
        co = np.array([(g0 * fn(k * ph)[:, None, None]).sum(axis=0) / 6 for k in (1, 2) for fn in (np.cos, np.sin)])
        return ok, mean, co
    ok1, m1, c1 = reduce(4)   # 1 degree, everywhere
    ok2, m2, c2 = reduce(2)   # 0.5 degree, kept only near land where the coastal gradients are
    near = np.zeros_like(ok2)
    for di in range(-2, 3):
        for dj in range(-2, 3):
            near |= ~np.roll(np.roll(ok2, di, 0), dj, 1)
    keep = ok2 & near
    q16 = lambda ok, mean: np.where(ok, np.round(mean * 100), -32768).astype('<i2')
    q8 = lambda ok, co: np.where(ok[None], np.clip(np.round(co * 8), -127, 127), 0).astype(np.int8)
    s0 = np.full((nlat, nlon), 0xFFFF, dtype='<u2'); sh = np.zeros((4, nlat, nlon), dtype=np.int8)
    ns = 0
    for i in range(nlat):
        for j in range(nlon):
            s = Sc[:, i, j].copy()
            if np.isfinite(s).sum() < 8:
                continue
            # months far from the median of the year are analysis artefacts (seen in the Arabian Gulf): leave them out of the fit
            med = np.nanmedian(s); mad = np.nanmedian(np.abs(s - med))
            s[np.abs(s - med) > max(2.5 * 1.4826 * mad, 0.4)] = np.nan
            cs = harmonics(s)
            if cs is not None:
                s0[i, j] = int(round(float(np.nanmedian(s)) * 100)); sh[:, i, j] = np.clip(np.round(cs[1:] * 20), -127, 127); ns += 1
    B.log('ocean: %d salinity cells; temperature: %d cells at 1 degree, %d coastal cells at 0.5 degree' % (ns, int(ok1.sum()), int(keep.sum())))
    yrs = '%d-%d' % (B.SST_YEARS[0], B.SST_YEARS[-1])
    ocean = {'source': 'Salinity: SeaDataCloud global climatology V2.1 (SeaDataNet; EMODnet Physics ERDDAP), 5 m level. Temperature: NOAA Coral Reef Watch CoralTemp monthly mean sea-surface temperature (NOAA CoastWatch ERDDAP)',
             'vintage': mtime_month(*glob.glob(os.path.join(cache, 'ocean/Salinity_*.nc')), *glob.glob(os.path.join(cache, 'sst/crw_*.nc'))),
             'period': 'salinity: climatological months from observations 1955-2019; temperature: mean of each calendar month ' + yrs, 'sstPeriod': yrs,
             'step': 1, 'lat0': -80, 'lon0': -180, 'nlat': nlat, 'nlon': nlon, 's0': pack(s0), 'sh': pack(sh), 't0': pack(q16(ok1, m1)), 'th': pack(q8(ok1, c1)),
             'fine': {'step': 0.5, 'lat0': -80, 'lon0': -180, 'nlat': 320, 'nlon': 720, 't0': pack(q16(keep, m2)), 'th': pack(q8(keep, c2))}}
    return write_module(out, 'atlas_ocean.js', [
        'Built-in world atlas — near-surface salinity and temperature of the sea. Generated by tools/atlas_build.py; do not edit.',
        '80 S - 80 N. Salinity: SeaDataCloud global climatology V2.1 (0.25 degree, monthly, 5 m level) on 1 degree cells, per cell',
        'the median of the year (g/kg x 100; 65535 = land or no data). Temperature: NOAA CoralTemp monthly mean sea-surface',
        'temperature (5 km, sampled every 0.25 degrees), mean of each calendar month %s, on 1 degree cells everywhere and on' % yrs,
        '0.5 degree cells (`fine`) within two cells of land (annual mean degC x 100; -32768 = land or not stored). Both carry the',
        'first two harmonics of the seasonal cycle (salinity x 20, temperature x 8):',
        'value(month m) = mean + a1 cos(2 pi m/12) + b1 sin(2 pi m/12) + a2 cos(4 pi m/12) + b2 sin(4 pi m/12).'], {'OCEAN': ocean})


# ------------------------------------------------------------------------------------------------ climate
def build_climate(cache, out):
    nlat, nlon = 140, 360  # 60 S ... 80 N, 1 degree
    grids, header = {}, None
    for par in B.POWER_PARAMS:
        acc = np.zeros((13, nlat, nlon)); cnt = np.zeros((nlat, nlon))
        for path in glob.glob(os.path.join(cache, 'power/%s_*.json' % par)):
            j = json.load(open(path))
            header = header or j.get('header')
            for ft in j.get('features', []):
                lo, la = ft['geometry']['coordinates'][:2]
                p = ft['properties']['parameter'][par]
                v = [p.get(m, -999) for m in MONTHS] + [p.get('ANN', -999)]
                if min(v) < -900:
                    continue
                i, jx = int(math.floor(la + 60)), int(math.floor(lo + 180)) % 360
                if 0 <= i < nlat:
                    acc[:, i, jx] += v; cnt[i, jx] += 1
        grids[par] = np.where(cnt > 0, acc / np.maximum(cnt, 1), np.nan)
        B.log('climate %s: %d of %d cells' % (par, int((cnt > 0).sum()), nlat * nlon))
    scale = {'ALLSKY_SFC_SW_DWN': (25, 0), 'WS10M': (12, 0), 'T2M': (2.5, 60)}  # stored = (value + offset) * scale
    hscale = {'ALLSKY_SFC_SW_DWN': 25, 'WS10M': 12, 'T2M': 4}
    ann, har = {}, {}
    ph = 2 * np.pi * np.arange(12) / 12
    for par, g in grids.items():
        k, off = scale[par]
        a = np.where(np.isfinite(g[12]), np.clip(np.round((g[12] + off) * k), 0, 254), 255).astype(np.uint8)
        ann[par] = pack(a)
        # seasonal cycle on 2 degree cells: first two harmonics of the monthly departures from the annual mean
        m = g[:12] - g[:12].mean(axis=0)
        import warnings
        with warnings.catch_warnings():
            warnings.simplefilter('ignore')
            m2 = np.nanmean(m.reshape(12, nlat // 2, 2, nlon // 2, 2), axis=(2, 4))
        m2 = np.nan_to_num(m2)
        co = [(m2 * f(q * ph)[:, None, None]).sum(axis=0) / 6 for q in (1, 2) for f in (np.cos, np.sin)]
        har[par] = pack(np.clip(np.round(np.array(co) * hscale[par]), -127, 127).astype(np.int8))
    climate = {'source': 'NASA POWER climatology (CERES SYN1deg irradiance, MERRA-2 wind and temperature)', 'vintage': mtime_month(*glob.glob(os.path.join(cache, 'power/*.json'))),
               'period': '%s-%s' % ((header or {}).get('start', '2001')[:4], (header or {}).get('end', '2020')[:4]), 'lat0': -60, 'lon0': -180, 'nlat': nlat, 'nlon': nlon, 'step': 1, 'hstep': 2,
               'ghi': {'k': 25, 'off': 0, 'hk': 25, 'ann': ann['ALLSKY_SFC_SW_DWN'], 'har': har['ALLSKY_SFC_SW_DWN']},
               'wind': {'k': 12, 'off': 0, 'hk': 12, 'ann': ann['WS10M'], 'har': har['WS10M']},
               'temp': {'k': 2.5, 'off': 60, 'hk': 4, 'ann': ann['T2M'], 'har': har['T2M']}}
    return write_module(out, 'atlas_climate.js', [
        'Built-in world atlas — long-term solar, wind and air-temperature resource. Generated by tools/atlas_build.py; do not edit.',
        'Source: NASA POWER climatology API, 2001-2020. Annual means on a 1 degree grid, 60 S - 80 N (all-sky global horizontal',
        'irradiation kWh/m2/d, wind speed at 10 m m/s, air temperature at 2 m degC; stored = (value + off) * k, 255 = no data)',
        'and the first two harmonics of the seasonal cycle on a 2 degree grid (x hk).'], {'CLIMATE': climate})


# ------------------------------------------------------------------------------------------------ nations
def build_nations(cache, out):
    from shapely.geometry import shape
    nd = os.path.join(cache, 'nations')
    codes = {r['ISO3166-1-Alpha-2']: r for r in csv.DictReader(open(os.path.join(nd, 'codes.csv'), encoding='utf-8')) if r['ISO3166-1-Alpha-2']}
    merge = {'N. Cyprus': ('CY', 'CYP', 'Cyprus'), 'Somaliland': ('SO', 'SOM', 'Somalia')}
    countries, order, blob = {}, [], []
    for ft in json.load(open(os.path.join(nd, 'countries50.geojson'), encoding='utf-8'))['features']:
        p = ft['properties']
        a2, a3, name = p.get('ISO_A2_EH', '-99'), p.get('ISO_A3_EH', '-99'), p.get('NAME_LONG') or p.get('NAME')
        if p.get('NAME') in merge:
            a2, a3, name = merge[p['NAME']]
        if p.get('NAME') == 'Kosovo':
            a2, a3 = 'XK', 'XKX'
        if a2 in ('-99', '', None, 'AQ'):
            continue
        c = countries.get(a2)
        if c is None:
            c = countries[a2] = {'a2': a2, 'a3': a3 if a3 != '-99' else codes.get(a2, {}).get('ISO3166-1-Alpha-3', ''), 'name': name, 'rings': []}
            order.append(a2)
        g = shape(ft['geometry']).simplify(0.02, preserve_topology=True)
        for poly in (g.geoms if g.geom_type == 'MultiPolygon' else [g]):
            pts = []
            for x, y in poly.exterior.coords:
                q = (int(round(x * 100)), int(round(y * 100)))
                if not pts or pts[-1] != q:
                    pts.append(q)
            if len(pts) >= 4:
                c['rings'].append(pts)
    for a2 in order:  # outlines as one int16 stream: per ring  n, x0, y0, dx, dy, ...
        c = countries[a2]
        for pts in c['rings']:
            blob += [len(pts), pts[0][0], pts[0][1]]
            for a, b in zip(pts, pts[1:]):
                blob += [b[0] - a[0], b[1] - a[1]]
        c['rings'] = len(c['rings'])
    # national figures: latest value and its year
    def wb(key):
        o = {}
        for r in json.load(open(os.path.join(nd, 'wb_%s.json' % key)))[1] or []:
            if r.get('value') is not None and r.get('countryiso3code'):
                o[r['countryiso3code']] = [float('%.4g' % r['value']), int(str(r['date'])[:4])]
        return o
    def owid(name):
        o = {}
        for r in list(csv.reader(open(os.path.join(nd, name), encoding='utf-8')))[1:]:
            try:
                if r[1]: o[r[1]] = [float('%.4g' % float(r[3])), int(r[4] or r[2])]
            except (ValueError, IndexError):
                pass
        return o
    tables = {k: wb(k) for k in B.WB}
    tables['gridCarbon'] = owid('owid_carbon.csv'); tables['renewableShare'] = owid('owid_renew.csv')
    fx = json.load(open(os.path.join(nd, 'fx.json')))
    for a2 in order:
        c = countries[a2]
        cur = (codes.get(a2, {}).get('ISO4217-currency_alphabetic_code') or '').split(',')[0].strip()
        if a2 == 'XK': cur = 'EUR'
        c['cur'] = cur if cur in fx['rates'] else (cur or '')
        c['v'] = {k: t[c['a3']] for k, t in tables.items() if c['a3'] in t}
    wbmeta = json.load(open(os.path.join(nd, 'wb_inflation.json')))[0]
    fxdate = datetime.datetime.utcfromtimestamp(fx['time_last_update_unix']).strftime('%Y-%m-%d')
    nations = {'source': 'Natural Earth admin-0 countries; World Bank Open Data; Our World in Data (Ember, Energy Institute); ISO 4217; open.er-api.com',
               'vintage': mtime_month(os.path.join(nd, 'wb_inflation.json')), 'wbUpdated': wbmeta.get('lastupdated', ''), 'fxDate': fxdate, 'scale': 100,
               'rings': pack(np.array(blob, dtype='<i2')), 'list': [countries[a] for a in order], 'fx': {k: float('%.6g' % v) for k, v in fx['rates'].items()}}
    B.log('nations: %d countries and territories, %d outlines, %d int16 values' % (len(order), sum(countries[a]['rings'] for a in order), len(blob)))
    return write_module(out, 'atlas_nations.js', [
        'Built-in world atlas — countries and national figures. Generated by tools/atlas_build.py; do not edit.',
        'Outlines: Natural Earth 1:50m admin-0 countries simplified to 0.02 degrees, outer rings only, packed as one int16',
        'stream in hundredths of a degree (per ring: n, x0, y0, dx, dy, ...; `rings` of each country in list order).',
        'Figures: [latest value, year] per indicator from World Bank',
        'Open Data (inflation, lending rate, GDP per capita, water stress, renewable electricity, business tariff US cents/kWh,',
        'renewable freshwater per capita, safely managed water) and Our World in Data (grid carbon gCO2/kWh, renewable share %).',
        'fx: units of currency per US dollar on fxDate.'], {'NATIONS': nations})


# ------------------------------------------------------------------------------------------------ coast
TIDES = {'M2': 28.9841042, 'S2': 30.0, 'N2': 28.4397295, 'K1': 15.0410686, 'O1': 13.9430356}  # degrees per hour
TIDE_EPOCH = '2026-01-01T00:00'


def _hours(ts):
    e = datetime.datetime.fromisoformat(TIDE_EPOCH)
    t0 = (datetime.datetime.fromisoformat(ts[0]) - e).total_seconds() / 3600
    return t0 + np.arange(len(ts))


def _arr(a):
    return np.array([np.nan if x is None else x for x in a], dtype=float)


def _sector_dir(d, w):
    """Predominant direction: weighted circular mean of the busiest 45 degree sector (and its neighbours)."""
    ok = np.isfinite(d) & np.isfinite(w)
    if ok.sum() < 10:
        return -1
    d, w = d[ok], w[ok]
    h = np.zeros(16)
    np.add.at(h, (np.floor(d / 22.5).astype(int)) % 16, w)
    k = int(np.argmax(h + np.roll(h, 1) + np.roll(h, -1)))
    sel = np.abs(((d - (k * 22.5 + 11.25) + 180) % 360) - 180) <= 33.75
    r = np.radians(d[sel])
    return int(round(math.degrees(math.atan2((w[sel] * np.sin(r)).sum(), (w[sel] * np.cos(r)).sum())) % 360)) % 360


def build_coast(cache, out):
    md = os.path.join(cache, 'marine')
    per = json.load(open(os.path.join(md, 'period.json')))
    sea_rows, miss = [], 0
    pts = B.marine_points(cache, B.SEA_STEP)
    for path in sorted(glob.glob(os.path.join(md, 'sea_*.json'))):
        b = int(os.path.basename(path)[4:9])
        j = json.load(open(path))
        j = j if isinstance(j, list) else [j]
        for k, loc in enumerate(j):
            h = loc['hourly']
            eta, sp, di = _arr(h['sea_level_height_msl']), _arr(h['ocean_current_velocity']) / 3.6, _arr(h['ocean_current_direction'])
            ok = np.isfinite(eta)
            if ok.sum() < 24 * 30:
                miss += 1; continue
            t = _hours(h['time'])
            cols = [np.ones(len(t)), (t - t.mean()) / 1000]
            for w in TIDES.values():
                cols += [np.cos(np.radians(w) * t), np.sin(np.radians(w) * t)]
            A = np.stack(cols, axis=1)
            c, *_ = np.linalg.lstsq(A[ok], eta[ok], rcond=None)
            amp = [math.hypot(c[2 + 2 * q], c[3 + 2 * q]) for q in range(5)]
            pha = [math.degrees(math.atan2(c[3 + 2 * q], c[2 + 2 * q])) % 360 for q in range(5)]
            e = eta[ok]
            # typical range as the live connector measures it (2nd-98th percentile over about 8 days), median over the period
            win = [np.quantile(eta[s:s + 192][np.isfinite(eta[s:s + 192])], 0.98) - np.quantile(eta[s:s + 192][np.isfinite(eta[s:s + 192])], 0.02) for s in range(0, len(eta) - 191, 24) if np.isfinite(eta[s:s + 192]).sum() > 150]
            day = [np.nanmax(eta[s:s + 25]) - np.nanmin(eta[s:s + 25]) for s in range(0, len(eta) - 24, 12) if np.isfinite(eta[s:s + 25]).sum() > 20]
            sok = sp[np.isfinite(sp)]
            row = [round(pts[b + k][0] * 100), round(pts[b + k][1] * 100), round(float(np.median(win)) * 100) if win else round(float(np.quantile(e, .98) - np.quantile(e, .02)) * 100),
                   round(float(np.quantile(day, 0.95)) * 100), round(float(np.quantile(day, 0.05)) * 100), round(float(np.mean(e)) * 100)]
            for q in range(5):
                row += [min(32000, round(amp[q] * 1000)), round(pha[q] * 10) % 3600]
            row += [round(float(sok.mean()) * 1000) if len(sok) > 100 else -1, round(float(np.quantile(sok, 0.99)) * 1000) if len(sok) > 100 else -1, _sector_dir(di, sp)]
            sea_rows.append(row)
    wave_rows = []
    wpts = B.marine_points(cache, B.WAVE_STEP)
    for path in sorted(glob.glob(os.path.join(md, 'wave_*.json'))):
        b = int(os.path.basename(path)[5:10])
        j = json.load(open(path))
        j = j if isinstance(j, list) else [j]
        for k, loc in enumerate(j):
            h = loc['hourly']
            hs, tp, di = _arr(h['wave_height']), _arr(h['wave_period']), _arr(h['wave_direction'])
            ok = np.isfinite(hs)
            if ok.sum() < 24 * 200:
                miss += 1; continue
            mon = np.array([int(s[5:7]) - 1 for s in h['time']])
            p90 = np.quantile(hs[ok], 0.9)
            okt = ok & np.isfinite(tp)
            storm = okt & (hs >= p90)
            row = [round(wpts[b + k][0] * 100), round(wpts[b + k][1] * 100), round(float(hs[ok].mean()) * 100), round(float(np.quantile(hs[ok], 0.95)) * 100), round(float(hs[ok].max()) * 100),
                   round(float(tp[okt].mean()) * 100) if okt.sum() > 100 else -1, round(float(tp[storm].mean()) * 100) if storm.sum() > 20 else -1, _sector_dir(di, hs ** 2)]
            row += [round(float(hs[ok & (mon == m)].mean()) * 100) if (ok & (mon == m)).sum() > 100 else round(float(hs[ok].mean()) * 100) for m in range(12)]
            wave_rows.append(row)
    B.log('coast: %d tide/current points, %d wave points (%d without data)' % (len(sea_rows), len(wave_rows), miss))
    coast = {'source': 'Open-Meteo Marine API (sea level and currents: Mercator Ocean / Copernicus Marine global model with tides; waves: ECMWF ERA5-Ocean and wave models)',
             'vintage': mtime_month(*glob.glob(os.path.join(md, '*_*.json'))), 'seaPeriod': '%s to %s' % (per['start'], per['end']), 'wavePeriod': '%d-01-01 to %d-12-31' % (B.WAVE_YEAR, B.WAVE_YEAR),
             'tideEpoch': TIDE_EPOCH + 'Z', 'tideSpeeds': list(TIDES.values()), 'tideNames': list(TIDES),
             'sea': {'cols': 19, 'rows': len(sea_rows), 'step': B.SEA_STEP, 'data': pack(np.array(sea_rows, dtype='<i2'))},
             'wave': {'cols': 20, 'rows': len(wave_rows), 'step': B.WAVE_STEP, 'data': pack(np.array(wave_rows, dtype='<i2'))}}
    return write_module(out, 'atlas_coast.js', [
        'Built-in world atlas — tides, currents and waves of coastal waters. Generated by tools/atlas_build.py; do not edit.',
        'Source: Open-Meteo Marine API, one representative sea point per grid cell that holds a shoreline, 56 S - 72 N.',
        'sea rows (int16): lat x100, lon x100, typical tidal range cm, spring range cm, neap range cm, mean level cm,',
        '  five harmonic constituents (amplitude mm, phase 0.1 deg; eta = sum A cos(w (t - tideEpoch) - phase)),',
        '  mean current mm/s, 99th-percentile current mm/s, predominant current direction deg (towards).',
        'wave rows (int16): lat x100, lon x100, mean Hs cm, 95th-percentile Hs cm, largest Hs cm, mean period cs,',
        '  mean period of the highest 10 % cs, predominant direction deg (from), mean Hs of each month cm.'], {'COAST': coast})


def build(cache, out):
    total = 0
    for name, fn in (('relief', build_relief), ('ocean', build_ocean), ('climate', build_climate), ('nations', build_nations), ('coast', build_coast)):
        try:
            total += fn(cache, out)
        except FileNotFoundError as e:
            B.log('skipped %s: missing download (%s) — run the fetch stage first' % (name, e))
    B.log('total size of the modules written in this run: %.1f kB' % (total / 1000))
