"""Rebuild js/data/atlas.js (offline world atlas).
Inputs in the working directory:
  Salinity.csv, Temperature.csv  — ERDDAP griddap CSV of SDC_GLO_CLIM_TS_V2_1, all 12 months, 5 m level,
                                    latitude (-76):16:(76), longitude (-180):16:(176)  (a 4-degree grid)
  land.json                       — Natural Earth ne_110m_land.geojson
Usage: python3 tools/atlas.py OUT.js
"""
import csv, json, math, sys

def load(name):
    d = {}
    with open(name + '.csv') as f:
        r = csv.reader(f); next(r); next(r)
        for t, _dep, la, lo, v in r:
            try: x = float(v)
            except ValueError: x = float('nan')
            d.setdefault((round(float(la)), round(float(lo))), [float('nan')] * 12)[int(t[5:7]) - 1] = x
    return d

S, T = load('Salinity'), load('Temperature')
lats, lons = list(range(-76, 77, 4)), list(range(-180, 177, 4))
sal, t0, ta, tp = [], [], [], []
for la in lats:
    for lo in lons:
        s = sorted(x for x in S.get((la, lo), []) if x == x and 0 < x < 50)
        t = T.get((la, lo), [float('nan')] * 12); tv = [x for x in t if x == x and -3 < x < 40]
        if len(s) < 6 or len(tv) < 10:
            sal.append(-1); t0.append(0); ta.append(0); tp.append(0); continue
        mean = sum(tv) / len(tv); a = b = 0.0
        for m, x in enumerate(t):
            if x == x and -3 < x < 40:
                a += (x - mean) * math.cos(2 * math.pi * m / 12); b += (x - mean) * math.sin(2 * math.pi * m / 12)
        a *= 2 / len(tv); b *= 2 / len(tv)
        sal.append(round(s[len(s) // 2] * 10)); t0.append(round(mean * 10)); ta.append(round(math.hypot(a, b) * 10))
        tp.append(round((math.atan2(b, a) / (2 * math.pi) * 12) % 12 * 10))
rings = []
for f in json.load(open('land.json'))['features']:
    g = f['geometry']
    for p in (g['coordinates'] if g['type'] == 'MultiPolygon' else [g['coordinates']]):
        out = []
        for x, y in p[0]:
            q = (round(x, 1), round(y, 1))
            if not out or out[-1] != q: out.append(q)
        if len(out) >= 4: rings.append([c for pt in out for c in pt])
rings.sort(key=len, reverse=True)
head = ("// Built-in world atlas used when live data services cannot be reached (offline, or on a host that blocks them):\n"
        "// coarse sea-surface salinity and temperature climatology on a 4° grid (derived from the SeaDataCloud global\n"
        "// climatology, monthly temperature reduced to mean / annual amplitude / month of maximum) and simplified\n"
        "// public-domain coastlines (Natural Earth 1:110m) for the base map. Generated by tools/atlas.py.\n")
atlas = {'lat0': -76, 'lon0': -180, 'step': 4, 'nlat': len(lats), 'nlon': len(lons), 'sal': sal, 't0': t0, 'ta': ta, 'tp': tp}
open(sys.argv[1], 'w').write(head + 'export const ATLAS = ' + json.dumps(atlas, separators=(',', ':')) + ';\nexport const LAND = ' + json.dumps(rings, separators=(',', ':')) + ';\n')
