import re, json, sys
src, out = sys.argv[1], sys.argv[2]
def sections(name):
    t = open(f"{src}/{name}.txt", encoding="utf-8").read()
    parts = re.split(r"(?m)^(\d{1,2})\.\s+(.+)$", t)
    d = {}
    for i in range(1, len(parts), 3):
        n = int(parts[i]); body = parts[i+2].split("------")[0]
        paras = [p.strip() for p in body.split("\n") if p.strip()]
        d[n] = paras
    return d
LEAD = re.compile(r"^.*?\b(comprises|comprise|includes|include|uses|use|employ|specify|specifies|are|define|defines)\b\s*(the\s+)?", re.I)
def items(text):
    res = []
    for sent in re.split(r"(?<=[a-z\)])\.\s+", text):
        s = sent.strip().rstrip(".")
        if not s: continue
        s2 = LEAD.sub("", s, count=1)
        s2 = re.sub(r",?\s+and\s+(?=[^,]*$)", ", ", s2)
        for it in s2.split(","):
            it = it.strip()
            if 2 < len(it) < 90: res.append(it[0].upper() + it[1:])
    return res
eq, cvv, inp, outp, mod = [sections(n) for n in ("equations", "cvv", "input", "output", "modules")]
cat = {}
for n in range(1, 14):
    e = eq[n]
    c = {}
    for p in cvv[n]:
        m = re.match(r"(Calibration|Verification|Validation):\s*(.*)", p, re.S)
        if m: c[m.group(1).lower()] = m.group(2)
    mods = re.sub(r"^The required modules should include\s*", "", mod[n][0]).rstrip(".")
    mods = re.sub(r",\s+and\s+", ", ", mods)
    cat[n] = {
        "classical": items(e[0]), "hybrid": items(e[1]),
        "icbc": items(e[2]), "icbcText": e[2],
        "calibration": c.get("calibration", ""), "verification": c.get("verification", ""), "validation": c.get("validation", ""),
        "inputs": " ".join(inp[n]).split(" Taken together")[0], "outputs": " ".join(outp[n]),
        "modules": [m.strip()[0].upper() + m.strip()[1:] for m in mods.split(",") if m.strip()],
    }
open(out, "w", encoding="utf-8").write(
    "// Reference catalogue of equation families, IC/BC, calibration-verification-validation practice,\n// input/output data and modules for the 13 suites. Generated by tools/catalog.py from the project specification.\nexport const CATALOG = " + json.dumps(cat, ensure_ascii=False, indent=1) + ";\n")
for n in cat: print(n, len(cat[n]["classical"]), len(cat[n]["hybrid"]), len(cat[n]["icbc"]), len(cat[n]["modules"]))
